#!/usr/bin/env python

import wx
from wx.lib import plot
import serial, time, sys
from threading import Thread

from numpy import *

class BPO(Thread):

	SYNC_NONE = 0
	SYNC_RISE = 1
	SYNC_FALL = 2

	MODE_CONTINUOUS = 0
	MODE_ONESHOT = 1

	minRate = 1.
	maxRate = 5720.

	minV = 0.
	maxV = 6.

	phaseOffset = 0
	trigV = 0


	def __init__(self, port, skips, mode, sync, trigV):

		# Open BP serial device:
		try:
			self.serdev = serial.Serial(port=port, baudrate=115200)
		except:
			# Leave exception for calling function to deal with:
			raise

		# Perform default thread initialization:
		Thread.__init__(self)

		# Set oscilloscope options
		self.skips = skips
		self.mode = mode
		self.sync = sync
		self.trigV = trigV
		self.data = nan*ones(100)

		# Enter binary scripting mode:
		self.serdev.write('\n\n')
		time.sleep(0.1)
		self.serdev.write(''.join(['\x00' for i in range(20)]))
		time.sleep(0.1)

		# Start continuous voltage measurement mode:
		self.serdev.flushInput()
		self.serdev.write('\x15')
		time.sleep(0.1)

		self.wantAbort = False

		self.start()

	def run(self):

		if self.mode == self.MODE_CONTINUOUS:
			self.continuous_sample()

		elif self.mode == self.MODE_ONESHOT:
			self.oneshot_sample()
		
	def getV(self):

		resp = self.serdev.read(2)
		return (ord(resp[0])*256 + ord(resp[1]))*6.6/1024


	def trig_check(self, thisV, lastV):

		if self.sync == self.SYNC_RISE:
			return (thisV >= self.trigV) and (lastV < self.trigV)
		else:
			return (thisV <= self.trigV) and (lastV > self.trigV)


	def trig_init(self):

		if self.sync == self.SYNC_RISE:
			return self.maxV
		else:
			return self.minV


	def continuous_sample(self):

		while True:

			if self.sync != self.SYNC_NONE:

				phaseOffsetP = max(self.phaseOffset,0)
				phaseOffsetN = -min(self.phaseOffset,0)
				vbuffer = nan*ones(phaseOffsetP)

				# Wait for trigger condition:

				lastV = self.trig_init()

				while True:

					thisV = self.getV()
					if (phaseOffsetN):
						roll(vbuffer,1)
						vbuffer[0] = thisV

					if self.trig_check(thisV, lastV) or self.sync == self.SYNC_NONE:
							break
					lastV = thisV

					if self.wantAbort:
						self.shutdown()
						return

				# Adjust to account for positive phase offset:

				for i in range(phaseOffsetP):
					self.getV()

				# Add aquired data:

				self.data[0:phaseOffsetN] = vbuffer

				for i in range(phaseOffsetP,len(self.data)):
					self.data[i] = self.getV()

					if self.wantAbort:
						self.shutdown()
						return
			else:
				for i in range(len(self.data)):
					self.data[i] = self.getV()

					if self.wantAbort:
						self.shutdown()
						return


	def abort(self):
		self.wantAbort = True

	def shutdown(self):

		self.serdev.write(' ')
		time.sleep(0.1)
		self.serdev.flushInput()

		self.serdev.write('\x0f')
		time.sleep(0.1)
		self.serdev.flushInput()
		self.serdev.close()


class MainWindow(wx.Frame):

	# Define Bus Pirate port (temporary)
	port = '/dev/bus_pirate'

	def __init__(self, parent, title):

		# Call standard frame constructor:
		wx.Frame.__init__(self, parent, title=title, id=wx.ID_ANY, size=(500,480))

		# Add status bar:
		self.CreateStatusBar()

		# Set up Menus:
		self.MenuSetup()

		# Main panel:
		self.panel = wx.Panel(self)

		# Set up plot window:
		self.plotpanel = wx.Panel(self.panel)
		self.plotpanel.SetBackgroundColour('white')
		self.plot = plot.PlotCanvas(self.plotpanel)
		self.plot.SetGridColour('grey')

		self.TrigLevSlider = wx.Slider(self.plotpanel, wx.ID_ANY,
				50.*(BPO.maxV-BPO.minV), 100.*BPO.minV, 100.*BPO.maxV,
				style = wx.SL_VERTICAL | wx.SL_INVERSE)

		# Plot window panel sizers:
		self.plotsizer = wx.BoxSizer(wx.HORIZONTAL)
		self.plotsizer.Add(self.plot, 1, wx.EXPAND)
		self.plotsizer.Add(self.TrigLevSlider, 0, wx.EXPAND | wx.BOTTOM, 20)
		self.plotpanel.SetSizer(self.plotsizer)

		# Set up oscilloscope controls:
		self.contpanel = wx.Panel(self.panel, style=wx.BORDER_SUNKEN)
		self.SampleButton = wx.ToggleButton(self.contpanel, wx.ID_ANY, 'SAMPLE')
		self.SampleButton.SetBackgroundColour('green')

		self.SamplingBox = wx.StaticBox(self.contpanel, wx.ID_ANY, 'Sampling')
		self.RB_continuous = wx.RadioButton(self.contpanel, wx.ID_ANY, 'Continuous', style=wx.RB_GROUP)
		self.RB_singleshot = wx.RadioButton(self.contpanel, wx.ID_ANY, 'Single shot')
		self.FreqCheckBox = wx.CheckBox(self.contpanel, wx.ID_ANY, 'Spectrum')

		self.TriggeringBox = wx.StaticBox(self.contpanel, wx.ID_ANY, 'Triggering')
		self.RB_trigoff = wx.RadioButton(self.contpanel, wx.ID_ANY, 'No sync', style=wx.RB_GROUP)
		self.RB_trigrise = wx.RadioButton(self.contpanel, wx.ID_ANY, 'Rising edge')
		self.RB_trigfall = wx.RadioButton(self.contpanel, wx.ID_ANY, 'Falling edge')

		# Oscilloscope controls panel sizers:
		self.contsizer = wx.BoxSizer(wx.HORIZONTAL)
		self.contsizer.Add(self.SampleButton, 0, wx.EXPAND | wx.ALL, 20)

		self.SamplingBoxSizer = wx.StaticBoxSizer(self.SamplingBox, wx.VERTICAL)
		self.SamplingBoxSizer.Add(self.RB_continuous, 1)
		self.SamplingBoxSizer.Add(self.RB_singleshot, 1)
		self.SamplingBoxSizer.Add(self.FreqCheckBox, 1)
		self.contsizer.Add(self.SamplingBoxSizer, 1, wx.EXPAND | wx.RIGHT, 20)

		self.TriggeringBoxSizer = wx.StaticBoxSizer(self.TriggeringBox, wx.VERTICAL)
		self.TriggeringBoxSizer.Add(self.RB_trigoff,1)
		self.TriggeringBoxSizer.Add(self.RB_trigrise,1)
		self.TriggeringBoxSizer.Add(self.RB_trigfall,1)
		self.contsizer.Add(self.TriggeringBoxSizer, 1, wx.EXPAND)

		self.contpanel.SetSizer(self.contsizer)

		# Main panel sizers:
		self.sizer = wx.BoxSizer(wx.VERTICAL)
		self.sizer.Add(self.plotpanel, 1, wx.EXPAND)
		self.sizer.Add(self.contpanel, 0, wx.EXPAND)
		self.panel.SetSizer(self.sizer)

		# Bind event handlers:
		self.Bind(wx.EVT_TOGGLEBUTTON, self.OnSampleButton, self.SampleButton)
		self.Bind(wx.EVT_RADIOBUTTON, self.OnTrigRise, self.RB_trigrise) 
		self.Bind(wx.EVT_RADIOBUTTON, self.OnTrigFall, self.RB_trigfall) 
		self.Bind(wx.EVT_RADIOBUTTON, self.OnTrigOff, self.RB_trigoff) 
		self.Bind(wx.EVT_SLIDER, self.OnTrigLevAdjust, self.TrigLevSlider) 

		# Draw empty plot:
		self.ClearPlot()

		# Set up plot updating timer:
		self.timer = wx.Timer(self)
		self.Bind(wx.EVT_TIMER, self.OnUpdate, self.timer)

		# Set up oscilloscope defaults:
		self.OscilloscopeDefaultSetup()

		self.Show(True)


	def MenuSetup(self):

		# Create menu bar:
		menuBar = wx.MenuBar()

		# File menu:
		filemenu = wx.Menu()
		menuItemSave = filemenu.Append(wx.ID_ANY, "&Save", "Save sample to file")
		menuItemSave.Enable(False)

		filemenu.AppendSeparator()

		menuItemExit = filemenu.Append(wx.ID_EXIT, "E&xit", "Terminate the program.")
		self.Bind(wx.EVT_MENU, self.OnExit, menuItemExit)

		menuBar.Append(filemenu, "&File")

		# View menu:
		viewmenu = wx.Menu()
		self.menuItemViewGrid = viewmenu.Append(wx.ID_ANY, '&Grid', 'Toggle grid', kind=wx.ITEM_CHECK)
		self.Bind(wx.EVT_MENU, self.OnViewGrid, self.menuItemViewGrid)
		self.menuItemViewTrigLev = viewmenu.Append(wx.ID_ANY,
				'&Trigger Level', 'Toggle trigger level visibility',
				kind=wx.ITEM_CHECK)
		self.Bind(wx.EVT_MENU, self.OnViewTrigLev, self.menuItemViewTrigLev)

		menuBar.Append(viewmenu, '&View')

		# Help menu:
		helpmenu = wx.Menu()

		menuItemAbout = helpmenu.Append(wx.ID_ABOUT, "&About", "Information about this program.")
		self.Bind(wx.EVT_MENU, self.OnAbout, menuItemAbout)

		menuBar.Append(helpmenu, "&Help")

		# Assign menubar to frame:
		self.SetMenuBar(menuBar)
	
	def OscilloscopeDefaultSetup(self):
		self.mode = BPO.MODE_CONTINUOUS
		self.sync = BPO.SYNC_NONE
		self.trigV = 0.5*(BPO.maxV-BPO.minV)

	def ClearPlot(self):


		if self.menuItemViewTrigLev.IsChecked():
			triglev_dat = [(0,self.trigV),(100,self.trigV)]
			triglev_line = plot.PolyLine(triglev_dat, colour='red', style=wx.LONG_DASH, width=1)
			gc = plot.PlotGraphics([triglev_line], '', 'Sample', 'Voltage')
		else:
			gc = plot.PlotGraphics([], '', 'Sample', 'Voltage')

		self.plot.Draw(gc, xAxis=(0,100), yAxis=(-1,7))

	def OnViewGrid(self, event):
		self.plot.SetEnableGrid(self.menuItemViewGrid.IsChecked())

	def OnViewTrigLev(self, event):
		if not self.SampleButton.GetValue():
			self.ClearPlot()

	def OnAbout(self, event):

		about_msg = """
PirateScope v0.1
(C) 2010 Free Software Foundation

This software is distributed under the
terms of the GNU General Public License.
"""

		dlg = wx.MessageDialog(self, about_msg, "About PirateScope", wx.OK)
		dlg.ShowModal()
		dlg.Destroy()
	
	def OnExit(self, event):

		if self.SampleButton.GetValue():
			self.timer.Stop()
			self.bpo.abort()
			time.sleep(0.5)

		self.Close(True)
	
	def OnUpdate(self, event):

		data = [(i,self.bpo.data[i]) for i in range(len(self.bpo.data))]

		line = plot.PolyLine(data, colour='blue', width=2)

		if self.menuItemViewTrigLev.IsChecked():
			triglev_dat = [(0,self.trigV),(100,self.trigV)]
			triglev_line = plot.PolyLine(triglev_dat, colour='red', style=wx.LONG_DASH, width=1)
			gc = plot.PlotGraphics([line, triglev_line], '', 'Sample', 'Voltage')
		else:
			gc = plot.PlotGraphics([line], '', 'Sample', 'Voltage')

		self.plot.Draw(gc, xAxis=(0,100), yAxis=(-1,7))

	def OnSampleButton(self, event):

		if self.SampleButton.GetValue():

			# Fire up oscilloscope:
			try: 
				self.bpo = BPO(self.port, 0, self.mode, self.sync, self.trigV)
			except:
				msg = "Failed to open Bus Pirate port '" + self.port + "'.\nCheck USB connection."
				dlg = wx.MessageDialog(self, msg, "Error", wx.OK)
				dlg.ShowModal()
				dlg.Destroy()

				self.SampleButton.SetValue(False)
				return

			# Turn button red:
			self.SampleButton.SetBackgroundColour('red')

			# Display "STOP SAMPLING"
			self.SampleButton.SetLabel('    STOP\nSAMPLING')

			# Start plot timer (0.1s intervals):
			self.timer.Start(milliseconds=100)

		else:
			self.timer.Stop()
			self.bpo.abort()
			self.ClearPlot()

			# Turn button green:
			self.SampleButton.SetBackgroundColour('green')

			# Display "SAMPLING"
			self.SampleButton.SetLabel('SAMPLING')
	
	def OnTrigRise(self, event):
		self.sync = BPO.SYNC_RISE
		if self.SampleButton.GetValue():
			self.bpo.sync = self.sync

	def OnTrigFall(self, event):
		self.sync = BPO.SYNC_FALL
		if self.SampleButton.GetValue():
			self.bpo.sync = self.sync

	def OnTrigOff(self, event):
		self.sync = BPO.SYNC_NONE
		if self.SampleButton.GetValue():
			self.bpo.sync = self.sync
	
	def OnTrigLevAdjust(self, event):
		self.trigV = self.TrigLevSlider.GetValue()/100.
		if self.SampleButton.GetValue():
			self.bpo.trigV = self.trigV
		elif self.menuItemViewTrigLev.IsChecked():
			self.ClearPlot()


app = wx.App(False)
frame = MainWindow(None, 'PirateScope')
app.MainLoop()
